<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Async / await functions</title>
</head>

<body>
    <h1>Async / Await functions</h1>

    <script>

        // Loadscript using async/await
        const loadScript = async (src) => {
            return new Promise((resolve, reject) => {

                let script = document.createElement("script")
                script.src = src;
                script.onload = () => {
                    resolve(src + "         Success!!!")
                }
                document.head.append(script)
            })
        }

        const load = async () => {
            console.log("MiliSecons before load : " + new Date().getMilliseconds());
            let s = await loadScript("https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js")
            console.log(s);
            console.log("MiliSecons After load : " + new Date().getMilliseconds());
        }
        load()

        // Error handling 
        let p = () => {
            return new Promise((resolve, reject) => {
                setTimeout(() => {
                    reject("This promise is rejected.")
                }, 2000)
            })
        } 

        let f = async () => {
            try {
                let e = await p()
                console.log(e);
            }
            catch (err) {
                console.log("This is resolved by catch block......");
            }
        }
        f()

        // multiple promises 
        let p1 = async () => {
            return new Promise((resolve,reject) => {
                setTimeout(() =>{
                    resolve("This is first promise....")
                },3000)
            })
        }
        let p2 = async () => {
            return new Promise((resolve,reject) => {
                setTimeout(() =>{
                    resolve("This is second promise....")
                },1000)
            })
        }
        let p3 = async () => {
            return new Promise((resolve,reject) => {
                setTimeout(() =>{
                    resolve("This is third promise....")
                },2000)
            })
        }

        let result = async () =>{
            
            console.time("result")
            let r1 = await p1()
            let r2 = await p2()
            let r3 = await p3()
            console.log(r1, r2, r3);
            console.timeEnd("result")
            console.log("----Using await----");

            console.time("result")
            let r4 = p1()
            let r5 = p2()
            let r6 = p3()
            let value = await Promise.all([r4,r5,r6])
            console.log(r1, r2, r3);
            console.timeEnd("result")
            console.log("----Using Promise.all----");
        }
        result()

        // class HttpError extends Error {
        //     constructor(response) {
        //         super(`${response.status} for ${response.url}`);
        //         this.name = 'HttpError';
        //         this.response = response;
        //     }
        // }

        // async function loadJson(url) {
        //     let response = await fetch(url)
        //     if (response.status == 200) {
        //         return response.json();
        //     } else {

        //         throw new HttpError(response);
        //     }
        // }

        // // Ask for a user name until github returns a valid user
        // async function demoGithubUser() {
        //     let user;
        //     while (true) {

        //         let name = prompt("Enter a name?", "iliakan");
        //         try {
        //             user = await loadJson(`https://api.github.com/users/${name}`)
        //             break;
        //         }
        //         catch (err) {
        //             if (err instanceof HttpError && err.response.status == 404) {
        //                 alert("No such user, please reenter.");
        //             } else {
        //                 throw err;
        //             }
        //         }
        //     }

        //     alert(`Full name: ${user.name}.`);
        //     return user;

        // }
        // demoGithubUser();

    </script>
</body>

</html>